---
- name: Установка GPG ключа Zabbix  
  rpm_key:  
    state: present  
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX  

- name: Добавление репозитория Zabbix  
  yum_repository:  
    name: zabbix  
    description: Zabbix Official Repository  
    baseurl: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/  
    enabled: 1  
    gpgcheck: no  # Можно также оставить gpgcheck = 0, будет одно и то же  

- name: Установка zabbix-agent  
  dnf:  
    name: zabbix-agent  
    state: present  
    disable_gpg_check: true 

- name: Настройка zabbix-agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'

- name: Включение и запуск службы Zabbix Agent
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started